# Generated by Django 4.0.4 on 2022-05-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('depart', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('hired', models.IntegerField()),
            ],
        ),
    ]
